import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Suspense } from 'react';

import NavBar from './components/NavBar';
import './globals.css';
import { QueryProvider } from './services/react-query';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen">
        <NavBar />
        <main className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {' '}
          <QueryProvider>
            <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          </QueryProvider>
        </main>
      </body>
    </html>
  );
}
